# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64018bd7e1aaa3c524da5c9a637edbd9d30dfbd1cfbcc9a87eddc463e2cc32723ca92ff593a6cf54599f6f25a497e409fa4e44a481f718aeb6cf6aaebaa48190

test:
  secret_key_base: 480e34722acc25bc3df55beb74e28af0a04a482545de6f7583c0108acc32793404868533a309f3c0e920410bfb064afff319b1b2d4318c1277b9f79ed0905f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
